<a href="https://colab.research.google.com/github/Rohitkumar-88/ML_Projects/blob/Colab_Notebooks/Pytorch_with_tensors_examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Basic Tensor Operations - Creating, Reshaping, and Inspecting Tensors**

In [10]:
import torch

#Create Tensors
a = torch.tensor([1,2,3]) #1D Tensor
b = torch.tensor([[1, 2], [3, 4]]) #2D Tensor

#Inspect Tensors
print(a.shape)
print(b.shape)
print("Data Type", b.dtype)
print("Device", b.device)

#Reshaping
c = torch.arange(1, 10).reshape(3, 3)
print("Reshaped Tensor:\n", c)


torch.Size([3])
torch.Size([2, 2])
Data Type torch.int64
Device cpu
Reshaped Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


**Elementwise Operations - Addition, Multiplication, and Broadcasting**

In [13]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

print("Elementwise addition: ", x + y )
print("Elementwise multiplication: ", x * y )

# Broadcasting (adding scalar to tensor)
z = torch.tensor([[1,2], [3, 4]])
print("Broadcast Addition:\n", z + 5)

Elementwise addition:  tensor([5, 7, 9])
Elementwise multiplication:  tensor([ 4, 10, 18])
Broadcast Addition:
 tensor([[6, 7],
        [8, 9]])


**Matrix Operations - Dot Product, Matrix Multiplication, Transpose, Inverse**

In [15]:
# Matrix multiplication

A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])

dot_product = torch.dot(torch.tensor([1, 2]), torch.tensor([3, 4])) # Dot product (1D tensors)
print("Dot Product:", dot_product)
matmul = torch.matmul(A, B) # Matrix multiplication
print("Matrix Multiplication:\n", matmul)




Dot Product: tensor(11)
Matrix Multiplication:
 tensor([[19, 22],
        [43, 50]])
